version: '3'
services:
  telegram-bot:
    build: .
    volumes:
     - .:/code
    depends_on:
    - mongo
  mongo:
    image: "mongo:latest"
    environment:
        - MONGO_INITDB_ROOT_USERNAME=telegramJiraAdmin
        - MONGO_INITDB_ROOT_PASSWORD=admin2321
