version: '3'
services:
  telegram-bot:
    build: .
    volumes:
        - .:/code
    depends_on:
        - mongo
  mongo:
    image: "mongo:latest"
    command: mongod
    volumes:
        - './tmp/data:/data/mongo'
